- hosts: localhost
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
       group: workstation
#       ansible_user: "{{ OPENTLC_ID }}"
       ansible_user: "cloud-user"
       ansible_ssh_private_key_file: "~/.ssh/openstack.pem"

- hosts: workstation
  become: yes
  roles:
    - { role: osp-servers, instance_name: "{{osp_servers.frontend.name}}", group: "{{osp_servers.frontend.meta[0].group}}", deployment: "{{osp_servers.frontend.meta[0].deployment_name}}", security_group_name: "{{osp_servers.frontend.security_group}}" }
    - { role: osp-servers, instance_name: "{{osp_servers.app1.name}}", group: "{{osp_servers.app1.meta[0].group}}", deployment: "{{osp_servers.app1.meta[0].deployment_name}}", security_group_name: "{{osp_servers.app1.security_group}}" }
    - { role: osp-servers, instance_name: "{{osp_servers.app2.name}}", group: "{{osp_servers.app2.meta[0].group}}", deployment: "{{osp_servers.app2.meta[0].deployment_name}}", security_group_name: "{{osp_servers.app2.security_group}}" }
    - { role: osp-servers, instance_name: "{{osp_servers.db.name}}", group: "{{osp_servers.db.meta[0].group}}", deployment: "{{osp_servers.db.meta[0].deployment_name}}", security_group_name: "{{osp_servers.db.security_group}}" }
