---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

#- name: download repos
#  get_url:
#    url: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
#    dest: /etc/yum.repos.d/internal.repo
#    mde: 0644

- name: enable repos
  copy:
    src: ../files/open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
