---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: download repos
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo.bak
    mode: 0644
 
# - name: install base tools and packages

